export enum contentType {
    JSON = "application/json",
    HTML = "text/html",
    PlainText = "text/plain",
    XML = "application/xml",
    FormUrlEncoded = "application/x-www-form-urlencoded",
    MultipartFormData = "multipart/form-data",
    JPEG = "image/jpeg",
    PNG = "image/png",
    GIF = "image/gif",
    WebP = "image/webp",
    PDF = "application/pdf",
    JavaScript = "application/javascript",
    CSS = "text/css",
    CSV = "text/csv",
    EventStream = "text/event-stream",
    OctetStream = "application/octet-stream",
    FontWOFF = "font/woff",
    FontWOFF2 = "font/woff2"
}
